# Generated by Django 4.1.5 on 2023-01-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
