# Generated by Django 4.1.5 on 2023-01-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='owner',
            new_name='user',
        ),
    ]
