# Generated by Django 4.1.5 on 2023-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
