# Generated by Django 4.1.5 on 2023-01-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='review',
            name='preview',
        ),
    ]
