# Generated by Django 4.1.5 on 2023-01-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_options_remove_review_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimages',
            name='review',
        ),
    ]
